GET http://localhost:3000/api/job

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "testuser2",
    "password": "password2"
}

### post a job
POST http://localhost:3000/api/job
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsInJvbGUiOiJ3b3JrcGxhY2UiLCJpYXQiOjE2MTAwMTg1ODJ9.a7JtG8gcR5ymBWx8Ip7a8ufmYanoBAOjHqBjOfte9yk

{
    "title": "wtf",
    "boy": {
        "description": "<script>alert(1)</script>",
        "contactInfo": "puh.nro 012 345 6789",
        "address": "Olemassaolon tie 55"
    }
}

###

DELETE http://localhost:3000/api/job?id=5ff5e554fe20864c14bfa516
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsInJvbGUiOiJ3b3JrcGxhY2UiLCJpYXQiOjE2MDk5NTA0NjV9.7Dx0lzbNI-AvZSxjVaMKlbMUlpTtAaJvE3AjF3mjl80
Host: localhost:3000
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"
Accept: application/json, text/plain, */*
DNT: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMSIsInJvbGUiOiJ3b3JrcGxhY2UiLCJpYXQiOjE2MTE3ODgyNTZ9.PMvW4CRohoBOohAELWdnKZiX46IS4Z6dahHeAkgJimU
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
Origin: http://localhost:3001
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:3001/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fi;q=0.8
###

# Get degrees
GET http://localhost:3000/api/degree