GET http://localhost:3000/api/job

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "58d771e2-a4da-4d9a-9418-61a35d2e33c4"
}

### post a job
POST http://localhost:3000/api/job
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjE1ODE3NTY5fQ.vB-OhGlHlnlm37IkgcjQPLo8TLGrfp1e1LycAUcmZFA

{
    "title": "wtf",
    "boy": {
        "description": "<script>alert(1)</script>",
        "contactInfo": "puh.nro 012 345 6789",
        "address": "Olemassaolon tie 55"
    }
}

###

DELETE http://localhost:3000/api/job?id=604f6d4df2a97b0bef72c1e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjE2NDU5MTczfQ.DT1XA9yNae9XLSKV-j9DXMknmdGlcpe8720ynTJ_e5g
###

# Get degrees
GET http://localhost:3000/api/degree
###

# Get all users as admin
GET http://localhost:3000/api/admin/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjE1ODE5NTI1fQ.D-ql_4o_cl_nNp76l69PGEHcxUa29QiplpfTuN36Hwk

# Delete user as admin
DELETE http://localhost:3000/api/admin/user?id=60593575f8fafd6a78046803
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjE2NDU5MjMzfQ.QsKubCMvU_j-HHLPeDEzOZqcz0F-ax-q4cKr3Xrejnw


###

# Try register without captcha
POST http://localhost:8080/api/register
Content-Type: application/json

{
    "username": "nnari",
    "email": "test"
}